import numpy as np

print("****1-D Array*******")
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr)
print("\nChecking dimensions of the created array-")
print(arr.ndim)
print("\nArray indexing")
print("\nArray element at index 0 and 2 are:")
print(arr[0])
print(arr[2])
print("\nAdding third and fourth elements from the array:")
print(arr[3] + arr[4])
print("\nArray slicing")
print('\nArray elements from index 1 to index 5-', arr[1:5])
print('\nElements from index 3-', arr[4:])
print('\nElements till index 4 only-', arr[:4])
print("\nNegative slicing")
print('\nSlices from index 3 from the end to index 1 from the end :', arr[-3:-1])
print("\n\n")
print("***Multidimensional Arrays*****")
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr1)
print("\nChecking dimensions of the created array-")
print(arr1.ndim)
print("\nAccessing 3rd element of the second array of the first array:")
print('\nThird element is- ', arr1[0, 1, 2])
print("****Operations on arrays*****")
arr2 = np.array([[5, 10], [20, 25]])
print(arr2)
print("\nMultiplying entire array by 4")
print(arr2 * 4)
print("\nSum of all elements in array-", arr2.sum())
print("\nSquare root of array elements- ", np.sqrt(arr2))
print("\nTranspose of arr2= ", arr2.T)
y = np.zeros([2, 5])
print("\nNew arr3 of all zeroes= ", y)
x = np.ones([2, 5])
print("\nNew arr4 of all ones= ", x)
print("\nNew arr3 shape: \n", y.shape)
print("\nNew arr4 shape: \n", x.shape)
